### ISSUE TITLE
the `.md` doesn't work for the index page

### ISSUE THREAD

**Issue by hamelsmu** [AnswerDotAI/claudette#22]
@jph00 when I click this it doesnt work on the home page (trying to get markdown for aimagic)

![image](https://github.com/user-attachments/assets/f900380f-6e13-4664-8cd3-72dfafe6e6a7)

**Comment by jph00** [comment]
That's really a quarto issue - I dunno that we can fix it at our end. Maybe you can raise an issue with them. FYI the actual file is here: https://claudette.answer.ai/index.html.md
