### ISSUE TITLE
How to properly handle model names?

### ISSUE THREAD

**Issue by just-kir** [AnswerDotAI/claudette#36]
I used something like this in my production code:
`models_aws[-1]`

Before 0.0.10 it was sonnet-3.5, and after 0.0.10 it became Haiku. Did not notice it for a while. What would be the correct way of using model names? 
I could do smth like this
`model = next(model for model in models_aws if 'claude-3-5' in model)`
but feels ugly.

**Comment by ncoop57** [comment]
@just-kir I'd recommend using the string explicitly since the `models_aws` var is simply a list of model names, especially in production settings due to inadvertent changes like this.
